apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebrowser.fullname" . }}
  namespace: {{ .Release.Namespace }} 
data:
  config.yaml: |+
    port: 80
    baseURL: "/{{ .Values.baseURL }}"
    address: ''
    database: "/etc/database.db"
    log: stdout
    plugin: ''
    scope: "/mnt/files"
    allowCommands: true
    allowEdit: true
    allowNew: true

