apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "filebrowser.fullname" . }}
  namespace: {{ .Release.Namespace }} 
  labels:
    app.kubernetes.io/name: {{ include "filebrowser.name" . }}
    helm.sh/chart: {{ include "filebrowser.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageClassName }}
